#! /bin/csh

# ========================================
# BUILD PATHS
# ========================================

## Pull information from the command line
set tmppath = $1

## Strip trailing forward slash from tmppath
echo ${tmppath} | rev | cut -c 2- | rev > ./tmp.txt
set tmppath = `cat ./tmp.txt`
rm ./tmp.txt
echo ${tmppath} # debug

## Strip trailing forward slash from inpath
cat ${tmppath}/in_path.txt | rev | cut -c 2- | rev > ./tmp.txt
set inpath = `cat ./tmp.txt`
rm ./tmp.txt
echo ${inpath} # debug

## Strip trailing forward slash from template path
cat ${tmppath}/template_path.txt | rev | cut -c 2- | rev > ./tmp.txt
set templatepath = `cat ./tmp.txt`
rm ./tmp.txt
echo ${templatepath} # debug

## Strip trailing forward slash from outpath
cat ${tmppath}/out_path.txt | rev | cut -c 2- | rev > ./tmp.txt
set outpath = `cat ./tmp.txt`
rm ./tmp.txt
echo ${outpath} # debug

## Access temp directory
cd ${tmppath} 

## Load params
set subj = `cat ./subject.txt`
set space = `cat ./space.txt`
set gm_prob = `cat ./gm_prob.txt`

echo ${subj}
echo ${space}
echo ${gm_prob}

# Select probability of GM to be defined as GM
3dcalc -a ${inpath}/sub-${subj}/anat/sub-${subj}_space-${space}_label-GM_probseg.nii.gz \
    -expr 'astep(a,'${gm_prob}')' \
    -prefix ${tmppath}/gm_out

# Downsample to BOLD resolution (using subject's rest template)
3dfractionize -template ${templatepath}/sub-${subj}/sub-${subj}_task-rest.scaled.resid.nii \
    -input ${tmppath}/gm_out+tlrc \
    -prefix ${tmppath}/gm_dwnsample_rough -clip .2

# Binarize the output
3dcalc -a ${tmppath}/gm_dwnsample_rough+tlrc \
    -expr 'step(a)' -prefix ${tmppath}/gm_dwnsample

cd ${tmppath}

# Generate NIFTI version
3dAFNItoNIFTI gm_dwnsample+tlrc 

# Move to final position
mv gm_dwnsample.nii ${outpath}/sub-${subj}_gm_mask.nii
